### PR TITLE
Add Touch Bar / Touch ID support

### PR DESCRIPTION
**Pull request by pkamb**
The Macbook Pro with Touch Bar has a physical Touch ID button that can be clicked. This key also functions as the notebook's power key.

This PR allows PowerKey to work with the Touch ID button. Single-tap the Touch ID button to input Forward Delete or any of your favorite PowerKey scripts or commands.

Many thanks to JD Lien (@jdlien) for his work in this branch! I made a few small changes, mainly to fix Xcode warnings. The initial PR was here:
https://github.com/pkamb/PowerKey/pull/54

Apple support site for the `Touch ID (power button)` key:
https://support.apple.com/en-us/HT207054

macbook-pro-2017-touchbar-touch-id-tech-spec

### CODE REVIEW

**Comment by pkamb** [comment]
@jdlien I removed the handler for triple clicks on the Touch ID button. Do you find yourself using that? I think I'd prefer to leave the triple-click accessibility handler in place, and only intercept single taps of the key.

**Comment by jdlien** [comment]
I didn't *really* use it, but I mainly put it there because the response to clicking the delete key is slow... so you could easily find yourself triple-clicking it if you wanted to delete three things quickly, and then you'd get the accessibility menu.

So if you're removing that, users need to be cognizant of the fact that they have to click the button -slowly- if they are clicking multiple times. I'm sure this is one of those things that users would get used to... unless, of course, you're able to find a way to eliminate that delay in the click. I have no idea how you'd do that... the old Eject key had a similar problem, but I think this is implemented differently.

**Comment by pkamb** [comment]
Good point. Re-added after testing a bit... tapping it fast now either hits the single or triple click, and activates PowerKey in either case. Feels more natural.

May need a setting for this at a later date if people are needing the accessibility shortcut as well. But it may be that you'll want to use one or the other, in which case this isn't a problem.

**Comment by jdlien** [comment]
Good idea. I think this would be a good option for people that might need that shortcut. Or possibly they could assign it to something else.

**Comment by pkamb** [comment]
Touch Bar support has been released in version 1.6!
https://github.com/pkamb/PowerKey/releases

**Pull request merged**
